version: '3.8'

services:
  mlflow:
    image: mlflow-server
    build:
      context: .
    ports:
      - "5000:5000" # Porta onde o servidor MLflow estará acessível
    environment:
      BACKEND_STORE_URI: sqlite:///mlflow.db # Banco de dados para armazenar metadados do MLflow
      ARTIFACT_ROOT: /app/mlruns # Diretório para os artefatos
    volumes:
      - ./mlruns:/app/mlruns # Persistência dos artefatos no host
      - ./mlflow.db:/app/mlflow.db # Persistência do banco de dados no host
    restart: unless-stopped
